import{a as b,S as v,i as a}from"./assets/vendor-b0d10f48.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();async function g(e,r,s){const i="https://pixabay.com/api/",t={key:"44102450-6df98fde061003ef9a12efa89",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:s};try{return(await b.get(i,{params:t})).data}catch(o){throw new Error(`HTTP error! status: ${o.response.status}`)}}function S(e){return`
        <a class="gallery-link" href="${e.largeImageURL}">
            <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-item-image">
            <ul class="info">
                <li class="info-title">Likes<span class="info-value">${e.likes}</span></li>
                <li class="info-title">Views<span class="info-value">${e.views}</span></li>
                <li class="info-title">Comments<span class="info-value">${e.comments}</span></li>
                <li class="info-title">Downloads<span class="info-value">${e.downloads}</span></li>
            </ul>
        </a>
    `}function p(e){return e.map(S).join("")}const P=document.querySelector(".search-form"),u=document.querySelector(".gallery"),m=document.querySelector(".loader"),d=document.querySelector(".load-more");let l="",n=1;const h=15,w=new v(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});y();async function q(e){if(e.preventDefault(),l=e.target.elements.searchQuery.value.trim(),n=1,!l){a.info({position:"topRight",message:"Please enter a search query"});return}u.innerHTML="",f(),L();try{const r=await g(l,n,h);if(r.hits.length===0){a.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}const s=p(r.hits);u.insertAdjacentHTML("beforeend",s),w.refresh(),n<totalPages?R():a.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})}catch(r){a.warning({title:"Error",message:`Something went wrong. ${r.message}`})}finally{e.target.reset(),y()}}async function $(){n+=1,L();try{const e=await g(l,n,h),r=p(e.hits);u.insertAdjacentHTML("beforeend",r),w.refresh(),T(),n>=totalPages&&(f(),a.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."}))}catch(e){a.info({position:"topRight",message:`We're sorry, but you've reached the end of search results. ${e.message}`}),f()}finally{y()}}P.addEventListener("submit",q);d.addEventListener("click",$);function L(){m.style.display="block"}function y(){m.style.display="none"}function R(){d.style.display="block"}function f(){d.style.display="none"}function T(){const r=document.querySelector(".gallery").querySelector(".gallery-link");if(r){const s=r.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}}
//# sourceMappingURL=commonHelpers.js.map
